### ISSUE TITLE
Water subsplash shows in a location different than the character hitting water

### ISSUE THREAD

**Issue by szymor** [szymor/soulfu#9]
After jumping into water, circular splash shows in a different location.

First seen at commit: https://github.com/szymor/soulfu/commit/0be4af6db88a4a1760d7cd7d479c861c3751a306 , after implementating pack/unpack

Platform: Arch Linux 64 bit

Possible cause: memory overwrite by libpulseaudio

Unrelated stack dump:
Old value = "ROOMWATERLEVEL\000 0.900000 -64.133995 0.020000 0.145000 1.900000 0.500000 ", '\000' <repeats 183 times>
New value = "\nOOMWATERLEVEL\000 0.900000 -64.133995 0.020000 0.145000 1.900000 0.500000 ", '\000' <repeats 183 times>
0xc48924d7 in pa_mainloop_dispatch () from /usr/lib32/libpulse.so.0
(gdb) bt
#0  0xc48924d7 in pa_mainloop_dispatch () from /usr/lib32/libpulse.so.0
#1  0xc4892d33 in pa_mainloop_iterate () from /usr/lib32/libpulse.so.0
#2  0xc4892ded in pa_mainloop_run () from /usr/lib32/libpulse.so.0
#3  0xc48a3e89 in ?? () from /usr/lib32/libpulse.so.0
#4  0xc4834104 in ?? () from /usr/lib32/pulseaudio/libpulsecommon-17.0.so
#5  0xf7b4c137 in ?? () from /usr/lib32/libc.so.6
#6  0xf7be3d38 in ?? () from /usr/lib32/libc.so.6

Workaround for that issue is known (i.e. define Spawn() function in PSPLASH.SRC), but more detailed analysis is recommended.

**Comment by szymor** [comment]
It seems the issue is not related to sound after all. The bug was probably introduced in the standalone script compiler. Compiling PSPLASH.SRC with the internal script compiler fixes the issue.

**Comment by szymor** [comment]
Fixed by 70fadef8ee9af46b97d2698065d08fcf1bdfe20b. Look at **ssc** for details.
